version: "3.9"

services:
  order-postgres:
    image: postgres:15
    container_name: order-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_db
    ports:
      - "5433:5432"
    volumes:
      - order_pgdata:/var/lib/postgresql/data

  payment-postgres:
    image: postgres:15
    container_name: payment-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment_db
    ports:
      - "5432:5432"
    volumes:
      - payment_pgdata:/var/lib/postgresql/data

  order-service:
    build:
      context: ./order-service
    depends_on:
      - order-postgres
    environment:
      DB_HOST: order-postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: order_db
      DATABASE_URL: postgres://postgres:postgres@order-postgres:5432/order_db?sslmode=disable
    ports:
      - "8082:8080"

  payment-service:
    build:
      context: ./payment-service
    depends_on:
      - payment-postgres
    environment:
      DB_HOST: payment-postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: payment_db
      DATABASE_URL: postgres://postgres:postgres@payment-postgres:5432/payment_db?sslmode=disable
    ports:
      - "8083:8080"

volumes:
  order_pgdata:
  payment_pgdata:
