# Use official Node.js v18 image as the base image
FROM node:18

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy rest of the app
COPY . .

# Expose the app's port
EXPOSE 5000

# Command to run the app
CMD ["npm", "start"]
