version: "3.8"

services:
  # PostgreSQL Database Service
  db:
    image: postgres:13
    container_name: my-postgres
    environment:
      POSTGRES_USER: tanya
      POSTGRES_PASSWORD: mom26dad
      POSTGRES_DB: customers
    ports:
      - "5433:5432"  # Expose PostgreSQL on port 5433 outside of the container
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Node.js Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: tanya
      DB_PASSWORD: mom26dad
      DB_NAME: customers
      JWT_SECRET: yourSuperSecretKey
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    command: ["npm", "start"]

volumes:
  postgres_data:
    driver: local
